import React from 'react'

class HrmComponent extends React.Component{
    e = "1. Human Resource Management\n" +
        "2. HRM Meaning and Definition Human Resource Management is also a function of management, concerned with hiring, motivating and maintaining people in an organisation. It focuses on people in the organisation.\n" +
        "3. HRM Meaning and Definition <ul><li>Organisations does not only consist of building, machines or inventories. It is people they manage and staff the organisation </li></ul><ul><li>HRM applies management principles in procuring, developing, maintaining people in the organisation. </li></ul><ul><li>Aims at integrated decision making and decisions on different aspects of employees are consistent with other HR decisions </li></ul><ul><li>HR Decisions must influence effectiveness of the organisation leading to better service to customer and high quality product and services at reasonable price. </li></ul><ul><li>It is not confined to business establishment only, HRM is applicable also to the non business organisation, like government department, education, health care etc. </li></ul>\n" +
        "4. Definition <ul><li>Human Resource Management is a series of integrated decisions that form the employment relationship; their quality contributes to the ability of the organisations and the employees to achieve their objectives. </li></ul><ul><li> - Milkovich and Boudreau </li></ul>\n" +
        "5. Definition <ul><li>Human Resource Management is concerned with the people dimension in management. Since every organisation is made up of people, acquiring their services, developing their skills, motivating them to higher levels of performance and ensuring that they continue to maintain their commitment to the organisation are essential to achieving organisational objectives. This is true regardless of the type of organisation – government, business, education, health, recreation or social action. </li></ul><ul><li> - David A. Decenzo and Stephen P. Robbins </li></ul>\n" +
        "6. Definition <ul><li>Human Resource Management is the planning, organising, directing and controlling of the procurement, development, compensation, integration, maintenance and separation of human resources to the end that individual, organisational, and social objectives are accomplished. </li></ul><ul><li> - Edwin B. Flippo </li></ul>\n" +
        "7. Scope of HRM HRM Nature Introduction Procurement Prospects Industrial Relations Remuneration Motivation Maintenance\n" +
        "8. Difference Between HRM and PM - 1 Fast Slow Speed of decision 8 Integrated Piecemeal Initiatives 7 Customer Labour Key relations 6 Nurturing Monitoring Managerial task vis-à-vis labour 5 Values/mission Norms/ customs & practices Behaviour referent 4 Business need Procedures Guide to management action 3 Impatience with rules Importance of devising clear rules Rules 2 Aim to go beyond contract Careful dimension of written contract Employment contract 1 HRM PM Dimension S.No\n" +
        "9. Difference Between HRM and PM - 2 Team work Division of labour Job design 17 Few Many Job categories and grades 16 Individual contracts Collective bargaining contracts Labour management 15 HRM PM Dimension S.No Harmonisation Separately negotiated Conditions 14 Performance related Job evaluation Pay 13 Integrated Separate Selection 12 Facilitation Negotiation Management skill 11 Direct Indirect Communication 10 Transformational Transactional Management role 9\n" +
        "10. Difference Between HRM and PM - 3 HRM PM Dimension S.No Latest Precedes HRM Evolution 23 Mutuality of interests Organization interest is uppermost Shared interests 22 People are assets & to be used for benefit of organization Labour – a tool – expendable & replaceable Respect for employees 21 Cultural & structural strategies Personnel procedures Focus for attention for interventions 20 Learning Organization Controlled courses Training & Development 19 Climate & culture Temporary Conflict handling 18\n" +
        "11. <ul><li>Shift towards HRD </li></ul>\n" +
        "12. HRD and HR <ul><li>HR can be termed as Human Resource Function or HRM Human Resource Management </li></ul><ul><li>HRD Stands for Human Resource Development </li></ul>\n" +
        "13. HRD and HR HR is all encompassing HR includes HRD and more HR goes far beyond the traditional Personnel function HR is more proactive and change oriented HR needs competencies of a different nature from what the traditional personnel function required\n" +
        "14. Importance of HRM <ul><li>Human Resource Management is important to all managers despite their various functions because of the following reasons- </li></ul><ul><ul><li>Hire the right person for the job </li></ul></ul><ul><ul><li>Low attrition rate </li></ul></ul><ul><ul><li>Ensure people do their best </li></ul></ul><ul><ul><li>Time saved in not conducting useless interviews </li></ul></ul><ul><ul><li>Avoid legal action for any discrimination </li></ul></ul><ul><ul><li>Safety laws are not ignored </li></ul></ul><ul><ul><li>Equity towards employee in relation to salary etc. </li></ul></ul><ul><ul><li>Effective training </li></ul></ul><ul><ul><li>Avoid unfair labour practices </li></ul></ul>\n" +
        "15. <ul><li>HUMAN RESOURCE PLANNING </li></ul>\n" +
        "16. Human Resource Planning <ul><li>Human Resource Planning is the process of forecasting a firm’s future demand for, and supply of, the right type of people in the right number. </li></ul>\n" +
        "17. Definition <ul><li>Human Resource planning includes the estimation of how many qualified people are necessary to carry out the assigned activities, how many people will be available, and what, if anything, must be done to ensure that personnel supply equals personnel demand at the appropriate point in the future. </li></ul>\n" +
        "18. Definition <ul><li>Specifically, human resource planning is the process by which an organisation ensures that it has the right number and kind of people, at the right place, at the right time, capable of effectively and efficiently completing those tasks that will help the organisation achieve its overall objectives. Human resource planning translates the organisation’s objectives and plans into the number of worker needed to meet those objectives. Without a clear cut planning, estimation of an organisation’s human resource need is reduced to mere guesswork. </li></ul><ul><ul><ul><ul><ul><li>David A. Decenzo and Stephen P. Robbins </li></ul></ul></ul></ul></ul>\n" +
        "19. Importance of HRP <ul><li>Future personnel needs. </li></ul><ul><li>Helps in strategic planning </li></ul><ul><li>Creating high talented personnel </li></ul><ul><li>Global strategies </li></ul><ul><li>Foundation of personnel function </li></ul><ul><li>Increase investments in human resources </li></ul><ul><li>Resistance to change </li></ul>\n" +
        "20. Factors affecting HRP <ul><li>Type and strategy of organisation </li></ul><ul><li>Organisational growth cycle and planning </li></ul><ul><li>Environmental uncertainties </li></ul><ul><li>Time horizons </li></ul><ul><li>Type and quality of forecasting information </li></ul><ul><li>Nature of jobs being filled </li></ul><ul><li>Outsourcing </li></ul>\n" +
        "21. HR Demand Forecast <ul><li>Demand forecasting is the process of estimating the quantity and quality of people required to meet future needs of the organisation. </li></ul>\n" +
        "22. Forecasting Techniques <ul><li>Ratio trends analysis </li></ul><ul><li>Regression analysis </li></ul><ul><li>Work study techniques </li></ul><ul><li>Delphi techniques </li></ul><ul><li>Managerial judgments </li></ul>\n" +
        "23. HR Supply Forecast <ul><li>Supply forecast determines whether the HR department will be able to procure the required number of personnel. Specifically, supply forecast measures the number of people likely to be available from within and outside an organisation. </li></ul>\n" +
        "24. HR Supply Forecast <ul><li>The supply analysis covers: </li></ul><ul><ul><li>Existing human resources </li></ul></ul><ul><ul><li>Internal source of supply </li></ul></ul><ul><ul><li>External source of supply </li></ul></ul>\n" +
        "25. <ul><li>JOB ANALYSIS </li></ul>\n" +
        "26. Job <ul><li>Job may be defined as “collection or aggregation of tasks, duties and responsibilities which as a whole, are regarded as a regular assignment to individual employees.” </li></ul>\n" +
        "27. Job Analysis <ul><li>Job Analysis is the process of studying and collecting information relating to the operations and responsibilities of a specific job. The immediate products of this analysis are job description and job specification. </li></ul>\n" +
        "28. Job analysis involves following steps: <ul><li>Collecting and recording job information </li></ul><ul><li>Checking the job information for accuracy </li></ul><ul><li>Writing job description based on information </li></ul><ul><li>Using the information to determine the skill, abilities and knowledge </li></ul><ul><li>Updating the information from time to time </li></ul>\n" +
        "29. Job Description <ul><li>A list of job’s duties, responsibilities, reporting relationship, working conditions, and supervisory responsibilities. </li></ul>\n" +
        "30. Job Specification <ul><li>A list of job’s “human requirements” that is, the requisite education, skills, personality and so on. </li></ul>\n" +
        "31. JOB ANALYSIS A process of obtaining all pertinent job facts <ul><li>Job Description </li></ul><ul><li>Job Title </li></ul><ul><li>Location </li></ul><ul><li>Job summary </li></ul><ul><li>Duties </li></ul><ul><li>Machine tools etc </li></ul><ul><li>Material etc </li></ul><ul><li>Supervision </li></ul><ul><li>Working condition </li></ul><ul><li>Hazards </li></ul><ul><li>Job Specification </li></ul><ul><li>Education </li></ul><ul><li>Experience </li></ul><ul><li>Training </li></ul><ul><li>Initiative </li></ul><ul><li>Physical effort </li></ul><ul><li>Responsibilities </li></ul><ul><li>Communication skills </li></ul><ul><li>Emotional characteristics </li></ul><ul><li>Unusual sensory sight etc. </li></ul>\n" +
        "32. Use of Job Analysis Information Job description and Job Specification Recruiting & Selection Performance Appraisal Salary & Wages Training & Develop Career Planning Health & Safety Employee Discipline\n" +
        "33. <ul><li>RECRUITMENT </li></ul>\n" +
        "34. Recruitment <ul><li>It is the process of finding and attracting capable applicants for employment. The process begins when new recruits are sought and ends when their applications are submitted. The result is pool of applicants from which new employees are selected. </li></ul>\n" +
        "35. Initiating the Recruitment Process <ul><li>Prior to initiating a recruitment procedure, the following matters should be considered: </li></ul><ul><ul><li>Clarification of the scope and skill sets required to successfully perform the duties of the position </li></ul></ul><ul><ul><li>Review of the Job Fact Sheet or Position Description to ensure that the skills and abilities required coincide with the current expectations of the position. If they do not, then a position evaluation should be undertaken. </li></ul></ul><ul><ul><li>Review of the compensation available to the position (i.e. salary and benefit plans, etc.) </li></ul></ul><ul><ul><li>Analysis of the impact that the hiring will have on the budget </li></ul></ul>\n" +
        "36. Factors Governing recruitment <ul><li>External factors </li></ul><ul><li>Supply and demand </li></ul><ul><li>Unemployment rate </li></ul><ul><li>Labour Market </li></ul><ul><li>Political </li></ul><ul><li>Social </li></ul><ul><li>Sons of soil </li></ul><ul><li>Image </li></ul><ul><li>Internal factors </li></ul><ul><li>Recruitment policy </li></ul><ul><li>HRP </li></ul><ul><li>Size of the firm </li></ul><ul><li>Cost </li></ul><ul><li>Growth </li></ul><ul><li>Expansion </li></ul>Recruitment\n" +
        "37. Building Pool of Candidate INTERNAL EXTERNAL\n" +
        "38. SOURCES OF RECRUITMENT <ul><li>Current Employee </li></ul><ul><li>References from present </li></ul><ul><li>employee </li></ul><ul><li>Databank of former </li></ul><ul><li>applicants </li></ul><ul><li>Retired Employee </li></ul><ul><li>Former employee </li></ul><ul><li>Advertising </li></ul><ul><li>Employment agencies </li></ul><ul><li>Temporary help </li></ul><ul><li>Executive recruiters </li></ul><ul><li>Referrals and walk-ins </li></ul><ul><li>College recruiting </li></ul><ul><li>Company’s web site </li></ul><ul><li>Free and fee-paying </li></ul><ul><li>Website services </li></ul>INTERNAL EXTERNAL\n" +
        "39. Recruiting Yield Pyramid <ul><li>It is the historical arithmetic relationships between- </li></ul><ul><ul><li>Recruitment leads and invitees </li></ul></ul><ul><ul><li>Invitees and interviews </li></ul></ul><ul><ul><li>Interviews and offers made </li></ul></ul><ul><ul><li>Offers made and offers accepted </li></ul></ul>\n" +
        "40. 50 100 150 200 1200 Leads generated (6:1) Candidates invited (4:3) Candidates interviewed (3:2) Offers made (2:1) New hires Recruiting Yield Pyramid\n" +
        "41. <ul><li>Internal </li></ul><ul><li>versus </li></ul><ul><li>External </li></ul><ul><li>Recruitment </li></ul><ul><li>Advantages & Disadvantages </li></ul>\n" +
        "42. Internal Recruitment 5. Morale problem for those not promoted 5. Good performance is rewarded 4. Politics play greater role 4. Enhancement of employee morale and motivation 3. Candidate’s current work may be affected 3. Organisation have better knowledge about the internal candidates 2. It abets raiding (make a person provide something) 2. Candidates are already oriented toward organisation 1. It perpetuates the old concept of doing things 1. It is less costly Disadvantages Advantages\n" +
        "43. External Recruitment 3. Chances of creeping in false positive or false negative error 3. Scope of resentment, jealousies and heartburn are avoided Disadvantages Advantages 2. It is costly 2. Compliance with reservation policy becomes easy 1. Better morale and motivation associated with internal recruiting is denied to the organisation 1. Benefits of new skill, new talent and experiences to organisation\n" +
        "44. <ul><li>SELECTION </li></ul>\n" +
        "45. Selection <ul><li>Selection is the process of differentiating between applicants in order to identify those with a greater likelihood of success in a job. </li></ul>\n" +
        "46. Selection <ul><li>The selection of a candidate with the right combination of education, work experience, attitude, and creativity will not only increase the quality and stability of the workforce, it will also play a large role in bringing management strategies and planning to fruition. </li></ul>\n" +
        "47. Factors affecting selection <ul><li>External environment </li></ul><ul><ul><li>Supply and demand of specific skill  </li></ul></ul><ul><ul><li>Unemployment rate </li></ul></ul><ul><ul><li>Legal and political considerations </li></ul></ul><ul><ul><li>Company’s Image </li></ul></ul>\n" +
        "48. Factors affecting selection <ul><li>Internal environment </li></ul><ul><ul><li>Company’s policy </li></ul></ul><ul><ul><li>HRP </li></ul></ul><ul><ul><li>Cost of hiring </li></ul></ul>\n" +
        "49. Process of selection Preliminary Interview Selection tests Employment Interview Reference & background Selection Decision Medical Examination Job Offer Employment Contract Evaluation R E J C T E D\n" +
        "50. Basic Testing Concepts <ul><li>Generally tests are administered to determine the applicant’s – </li></ul><ul><ul><li>Ability </li></ul></ul><ul><ul><li>Aptitude </li></ul></ul><ul><ul><li>Personality </li></ul></ul><ul><ul><li>Interest </li></ul></ul>\n" +
        "51. Basic Testing Concepts <ul><li>Ability tests </li></ul><ul><ul><li>Helps to determine how well one can perform his task </li></ul></ul>\n" +
        "52. Basic Testing Concepts <ul><li>Aptitude tests </li></ul><ul><ul><li>Helps to determine a persons potential to learn in a given area </li></ul></ul>\n" +
        "53. Basic Testing Concepts <ul><li>Personality tests </li></ul><ul><ul><li>To measure a prospective employee’s motivation to function in a particular working environment </li></ul></ul>\n" +
        "54. Basic Testing Concepts <ul><li>Interest tests </li></ul><ul><ul><li>To measure an individual’s activity preferences. (For career change or when there is multiple career option available) </li></ul></ul>\n" +
        "55. Selection Tests Locus of control ASUFA Measuring personality factors 16 PF Behaviour in work place PAPI Understanding personality type MBTI Identifying behavioural requirement for the job Thomas Profiling Description Tests\n" +
        "56. Interviews <ul><li>Formal, in depth conversation conducted to evaluate the applicant’s acceptability. </li></ul><ul><li>Adapted to unskilled, skilled, managerial and professional employees. </li></ul><ul><li>Two-way exchange of information, the interviewers learn about the applicant, and the applicant learns about the organization </li></ul>\n" +
        "57. Shortcomings of interviews <ul><li>Absence of reliability </li></ul><ul><li>Lack of validity </li></ul><ul><li>Biases </li></ul>\n" +
        "58. Preparing for the Interview <ul><li>Abundant research exists that reliability and validity of the selection interview are higher when an interview is structured, planned and standardized in form. This approach fosters a comprehensive investigation of the applicant's background, precludes personal and non-job-related questions, and increases impartiality in qualification assessment. Therefore, an interview plan is strongly recommended . </li></ul><ul><li>Prior to developing the interview plan, it is critical to be clear about the job requirements and stick to them throughout the hiring process. This ensures that you “don’t fall in love with each candidate and redefine the job to fit”. </li></ul>\n" +
        "59. <ul><li>Types of Interview </li></ul>\n" +
        "60. Interview may be One to one Interview <ul><li>Only two participants – </li></ul><ul><li>Interviewer </li></ul><ul><li>Candidate </li></ul>\n" +
        "61. Sequential Interview 1 2 3 Involves series of interviews Candidates moves from room to room\n" +
        "62. Panel Interview Two or more interviewers Formal\n" +
        "63. Objectives of Interview <ul><li>Helps obtain additional information from applicant </li></ul><ul><li>Facilitates giving general information to applicant </li></ul><ul><li>Help build image of the organization </li></ul>"

    convertStr(e){

        for (let i=1; i<=63; i++){
            e = e.replace(`${i}.`,"%");
        }
        return e;
    }
    theRef = React.createRef();
    componentDidMount(){

        let str = this.convertStr(this.e).split("%");
        for (let i=1; i<str.length;i++){
            this.theRef.current.innerHTML += `<div className="col col-lg-12 col-md-12">${i}. ${str[i]}</div>`;
        }
    }
    render(){
        return(
            <div className="container">
                <div className="row" ref={this.theRef}>
                </div>
            </div>)
    }
}

export default HrmComponent;